---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381492007658:role/cloudwatch-agent
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
        - operator: Exists
      containers:
        - name: fluent-bit
          image: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.32.2.20240516
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 2020
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: dockerlogs
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: host-application-logs
              mountPath: /mnt/node-logs
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: 200Mi
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
        - name: dockerlogs
          hostPath:
            path: /var/lib/docker/containers
            type: Directory
        - name: host-application-logs
          hostPath:
            path: /logs
            type: DirectoryOrCreate
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-app-logs.conf
    @INCLUDE input-kube-containers.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-opensearch.conf

  input-app-logs.conf: |
    [INPUT]
        Name              tail
        Path              /mnt/node-logs/*/*.log
        Tag               applogs.*
        DB                /var/fluent-bit/state/applogs.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Refresh_Interval  5
        Rotate_Wait       30

  input-kube-containers.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Parser            cri
        DB                /var/fluent-bit/state/kube-containers.db
        Mem_Buf_Limit     100MB
        Skip_Long_Lines   On
        Refresh_Interval  5

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Merge_Log           On
        Keep_Log            Off
        Labels              On
        Annotations         Off

  output-opensearch.conf: |
    [OUTPUT]
        Name                opensearch
        Match               applogs.*
        Host                vpc-uat-oss-sa4m7otu6ck4fmp4fy2l5wkoce.us-east-1.es.amazonaws.com
        Port                443
        TLS                 On
        AWS_Auth            On
        AWS_Region          us-east-1
        AWS_Service_Name    es
        Index               app-logs
        Suppress_Type_Name  On
        Retry_Limit         False

    [OUTPUT]
        Name                opensearch
        Match               kube.*
        Host                vpc-uat-oss-sa4m7otu6ck4fmp4fy2l5wkoce.us-east-1.es.amazonaws.com
        Port                443
        TLS                 On
        AWS_Auth            On
        AWS_Region          us-east-1
        AWS_Service_Name    es
        Index               kube-logs
        Suppress_Type_Name  On
        Retry_Limit         False